M48
; DRILL file {KiCad (6.0.7)} date Fri Sep 23 13:32:56 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-23T13:32:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0600
%
G90
G05
T1
X4.5503Y-4.9793
X4.7471Y-4.9793
X6.8928Y-4.9793
X7.0896Y-4.9793
T0
M30
